// <auto-generated />
using System;
using DataSpaceMicroservice.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataSpaceMicroservice.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataSpaceMicroservice.Data.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvatarImageUrl");

                    b.Property<string>("DataSpaceDirName");

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DataSpaceMicroservice.Data.Models.DSDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NodeId");

                    b.Property<int?>("ParentDirectoryId");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("ParentDirectoryId");

                    b.ToTable("DSDirectories");
                });

            modelBuilder.Entity("DataSpaceMicroservice.Data.Models.DSFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MimeType");

                    b.Property<int>("NodeId");

                    b.Property<int?>("ParentDirectoryId");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("ParentDirectoryId");

                    b.ToTable("DSFiles");
                });

            modelBuilder.Entity("DataSpaceMicroservice.Data.Models.DSNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<DateTime>("LastModifiedTime");

                    b.Property<string>("Name");

                    b.Property<string>("NodeType")
                        .IsRequired();

                    b.Property<int>("OwnerId");

                    b.Property<string>("Path");

                    b.Property<bool>("Private");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("DSNodes");
                });

            modelBuilder.Entity("DataSpaceMicroservice.Data.Models.FileAccountShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountId");

                    b.Property<int>("FileId");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("FileId");

                    b.ToTable("FileAccountShares");
                });

            modelBuilder.Entity("DataSpaceMicroservice.Data.Models.DSDirectory", b =>
                {
                    b.HasOne("DataSpaceMicroservice.Data.Models.DSNode", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataSpaceMicroservice.Data.Models.DSDirectory", "ParentDirectory")
                        .WithMany("Directories")
                        .HasForeignKey("ParentDirectoryId");
                });

            modelBuilder.Entity("DataSpaceMicroservice.Data.Models.DSFile", b =>
                {
                    b.HasOne("DataSpaceMicroservice.Data.Models.DSNode", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataSpaceMicroservice.Data.Models.DSDirectory", "ParentDirectory")
                        .WithMany("Files")
                        .HasForeignKey("ParentDirectoryId");
                });

            modelBuilder.Entity("DataSpaceMicroservice.Data.Models.DSNode", b =>
                {
                    b.HasOne("DataSpaceMicroservice.Data.Models.Account", "Owner")
                        .WithMany("OwningNodes")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataSpaceMicroservice.Data.Models.FileAccountShare", b =>
                {
                    b.HasOne("DataSpaceMicroservice.Data.Models.Account", "Account")
                        .WithMany("SharedFiles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataSpaceMicroservice.Data.Models.DSFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
